routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/', function () {
//    return view('welcome');
//});

Route::get( '', 'HomeController@index' )->name( 'home' );

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('calculations', 'CalculationsController')->except(['destroy', 'edit', 'update', 'create']);

app/Calculations.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Http\Request;

class Calculations extends Model
{

	protected $fillable = [
		'title',
		'content'
	];

	protected $casts = [
		'content' => 'array'
	];

    public function user()
    {
    	return $this->belongsTo(User::class);
    }

	public function scopeSearch( $query, Request $request )
	{
		if ( $request->search ) {
			return $query->where( 'title', 'like', "%{$request->search}%" );
		}
	}
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
	    'email',
	    'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
	    'remember_token',
    ];

    public function calculations()
    {
        return $this->hasMany(Calculations::class);
    }
}

app/Http/Controllers/CalculationsController.php
<?php

namespace App\Http\Controllers;

use App\Calculations;
use App\Http\Requests\CalculationsRequest;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class CalculationsController extends Controller
{
	public function __construct() {
		$this->middleware('auth');
	}

	/**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index( Request $request )
    {
	    $calculations = Auth::user()
	                        ->calculations()
		                    ->search($request)
	                        ->orderBy('id', 'DESC')
	                        ->paginate(50);

	    return view('user.calculations.index')->withData($calculations);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CalculationsRequest $request) {

		Auth::user()->calculations()->create($request->all() );

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
	    $calculation = Auth::user()->calculations()->findOrFail($id);
//	    dd($calculation->content);
	    return view('user.calculations.show')->withData($calculation);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('home');
    }
}

resources/views/blocks/calculator.blade.php
<div class="container">
    <form id="calculator" class="form-inline mb-3">
        <div class="form-group col-12">
            <input type="text" name="calculator" class="viewer col-8 form-control mr-3">
            <button id="equals" class="equals btn btn-primary" type="submit" data-result="">=</button>
        </div>
    </form>

    @if(Auth::check())
        <form id="save-log" action="{{ route('calculations.store') }}" class="form-inline mb-3 col-12">
            <div class="form-group pr-1">
                {!! csrf_field() !!}
                <input type="text" name="log-name" placeholder="Log Name" class="form-control">
            </div>
            <button class="save-log btn btn-primary mr-1" type="submit">Save Log</button>
            <button class="clear-log btn btn-secondary">Clear Log</button>
        </form>
    @endif
    <div class="col-12">
        <code id="results"></code>
    </div>
</div>


@section('css')
    @parent
    <link rel="stylesheet" href="{{ asset('css/calculator.css') }}"/>
@stop

@section('js')
    @parent
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mathjs/5.0.0/math.min.js"></script>
    <script type="text/javascript" src="{{ asset('js/calculator.js') }}"></script>
@stop

resources/views/home.blade.php
@extends('layouts.app')

@section('content')

    @include('blocks.calculator')

@stop

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->


    <!-- Fonts -->
    <link rel="dns-prefetch" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Raleway:300,400,600" rel="stylesheet" type="text/css">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">

    <link href="{{ asset('css/style.css') }}" rel="stylesheet">
    @yield('css')
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light navbar-laravel">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                            </li>
                        @else
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('calculations.index') }}">Saved Logs</a>
                            </li>

                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>

    <footer></footer>

    <script src="{{ asset('js/app.js') }}"></script>

    @yield('js')
</body>
</html>

resources/views/user/calculations/index.blade.php
@extends('layouts.app')

@section('content')
    <div id="archive-page" class="container">

        <form action="{{ route('calculations.index', app()->getLocale()) }}" method="GET" class="form-inline mb-2">
            <div class="form-group col-12">
                <input type="text" class="form-control mb-3" id="search" placeholder="Search for a log" name="search">
                <button type="submit" class="btn btn-primary mb-3">Search</button>
            </div>

        </form>

        <div id="calcs" class="row">
            @foreach($data as $value)
                <div class="calc-wrap col-6 col-md-4">

                    <div class="card-header" id="heading">
                        <h5 class="mb-0">
                            <button type="button" data-extract="{{ route('calculations.show', $value->id) }}"
                                    class="btn btn-link btn-calc" data-toggle="modal" data-target="#modal">
                                {{ $value->title }}
                            </button>
                        </h5>
                    </div>

                </div>
            @endforeach

            <div class="modal fade" id="modal" tabindex="-1" role="dialog" aria-labelledby="modalLabel"
                 aria-hidden="true">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="modalLabel">

                            </h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">

                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>

                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
@stop


@section('js')
    @parent
    <script type="text/javascript" src="{{ asset('js/archive.js') }}"></script>
@stop

resources/views/user/calculations/show.blade.php
@foreach($data->content as $calcs)
    <p>{{ $calcs }}</p>
    <hr>
@endforeach